# Profile: 默认（未识别语言/框架）
# 只部署核心能力，不做任何语言特定配置

ENABLE_PUSH_GATE="y"
ENABLE_FORMAT="n"
ENABLE_BUILD_CHECK="n"
ENABLE_GIT_HOOKS="y"
ENABLE_CONFIG_FILES="y"
ENABLE_ACTIONS="n"
ENABLE_COMMUNITY="n"
ENABLE_TEST_SIGNAL="n"
ENABLE_PERF_SIGNAL="n"
ENABLE_REWARD_LOOP="n"

PROFILE_PROTECTED_PATHS="\.git/"
PROFILE_FROZEN_TESTS="*test*|*spec*"
