#!/usr/bin/env python3
"""
driver.py — 全自动进化循环驱动器

把所有组件串成一个完整的自治循环：
  observe → prompt → AI执行 → guardrail → 采集 → 判定 → 学习 → 熔断检查 → 循环

用法: python driver.py <signals.yaml> [--dry-run] [--single-round]

这是整个奖励信号系统的最顶层入口。
"""

import json
import os
import subprocess
import sys
import time
import yaml
from pathlib import Path
from datetime import datetime, timezone


SCRIPT_DIR = Path(__file__).parent


def load_yaml(path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def git(*args):
    r = subprocess.run(["git"] + list(args), capture_output=True, text=True)
    return r.stdout.strip(), r.returncode


def py_run(script, *args, check=True):
    """运行 Python 脚本。"""
    cmd = [sys.executable, str(SCRIPT_DIR / script)] + list(args)
    return subprocess.run(cmd, capture_output=False)


def generate_report(signals_dir, goal, trajectory, start_time, total_rounds):
    """生成人类可读的验收报告 report.md"""
    total_min = (time.time() - start_time) / 60
    pass_count = sum(1 for e in trajectory if e.get("overall") == "PASS")
    fail_count = sum(1 for e in trajectory if e.get("overall") == "FAIL")

    lines = [
        "# Evolution Report",
        "",
    ]
    if goal:
        lines.append(f"**Goal**: {goal}")
        lines.append("")

    # 结果判定
    if pass_count > 0:
        status = "COMPLETED" if fail_count == 0 else "PARTIAL"
    else:
        status = "FAILED"
    lines.append(f"**Result**: {status} ({pass_count} PASS / {fail_count} FAIL in {total_rounds} rounds, {total_min:.0f} min)")
    lines.append("")

    # 时间线
    lines.append("## Timeline")
    lines.append("")
    lines.append("| Round | Action | Result | SHA | Duration |")
    lines.append("|-------|--------|--------|-----|----------|")
    for e in trajectory:
        sha = e.get("commit_sha", "")[:7]
        desc = e.get("description", "")[:50]
        lines.append(
            f"| {e.get('round', '?')} "
            f"| {desc} "
            f"| {e.get('overall', '?')} "
            f"| {sha or '-'} "
            f"| {e.get('duration_sec', 0)}s |"
        )
    lines.append("")

    # 成功的改动
    passes = [e for e in trajectory if e.get("overall") == "PASS"]
    if passes:
        lines.append("## What was done")
        lines.append("")
        for e in passes:
            sha = e.get("commit_sha", "")[:7]
            lines.append(f"- `{sha}` {e.get('description', '')}")
        lines.append("")

    # 失败的尝试
    fails = [e for e in trajectory if e.get("overall") == "FAIL"]
    if fails:
        lines.append("## What was tried but didn't work")
        lines.append("")
        for e in fails:
            lines.append(f"- Round {e.get('round', '?')}: {e.get('description', '')}")
        lines.append("")

    # 阻断诊断（如果有）
    diag_path = os.path.join(signals_dir, "blocker-diagnosis.md")
    if os.path.exists(diag_path):
        lines.append("## Blockers")
        lines.append("")
        with open(diag_path, encoding="utf-8") as f:
            lines.append(f.read())
        lines.append("")

    lines.append("---")
    lines.append("*Generated by driver.py*")

    report = "\n".join(lines)
    report_path = os.path.join(signals_dir, "report.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)
    return report_path


def _capture_self_heal_context(branch, signals_dir):
    """从失败的分支中提取 self-heal 上下文，供下一轮使用。

    AI agent 在 SKILL 中被指示写 self-heal-log.md 和 docs/build-failures.md。
    这里把它们复制到 signals_dir，下一轮的 observe.py 会读取。
    """
    heal_context = []

    # 读取 AI 的 self-heal-log（如果写了）
    for log_name in ["self-heal-log.md", "docs/build-failures.md"]:
        content, rc = git("show", f"{branch}:{log_name}")
        if rc == 0 and content.strip():
            heal_context.append(f"## From {log_name}\n{content}")

    if heal_context:
        ctx_path = os.path.join(signals_dir, "self-heal-context.md")
        with open(ctx_path, "w", encoding="utf-8") as f:
            f.write("\n\n".join(heal_context))
        print(f"  Self-heal context saved: {ctx_path}")


def main():
    if len(sys.argv) < 2:
        print("用法:")
        print("  python driver.py <signals.yaml> --goal \"描述你的目标\"")
        print("  python driver.py <signals.yaml> [--dry-run] [--single-round]")
        sys.exit(1)

    config_path = sys.argv[1]
    dry_run = "--dry-run" in sys.argv
    single_round = "--single-round" in sys.argv

    # 读取 --goal 参数
    goal = ""
    if "--goal" in sys.argv:
        idx = sys.argv.index("--goal")
        if idx + 1 < len(sys.argv):
            goal = sys.argv[idx + 1]

    config = load_yaml(config_path)
    loop_cfg = config.get("loop", {})

    max_rounds = 1 if single_round else loop_cfg.get("max_rounds", 20)
    max_duration_min = loop_cfg.get("max_duration_min", 240)

    # 信号配置
    signals = [s for s in config.get("signals", []) if s.get("enabled", True)]
    merge_strategy = config.get("merge", {}).get("strategy", "all")

    # 路径
    history_cfg = config.get("history", {})
    signals_dir = history_cfg.get("history_file", ".signals/history.json")
    signals_dir = str(Path(signals_dir).parent)

    # 保存目标（供 prompt.py 和 circuit_breaker 读取）
    if goal:
        os.makedirs(signals_dir, exist_ok=True)
        with open(os.path.join(signals_dir, "goal.txt"), "w", encoding="utf-8") as f:
            f.write(goal)

    base_branch, _ = git("rev-parse", "--abbrev-ref", "HEAD")
    start_time = time.time()

    print("=" * 60)
    print("  Autonomous Evolution Loop")
    if goal:
        print(f"  Goal: {goal}")
    print(f"  Signals: {', '.join(s['name'] for s in signals)}")
    print(f"  Strategy: {merge_strategy}")
    print(f"  Max rounds: {max_rounds} | Max time: {max_duration_min}m")
    print(f"  Base: {base_branch}")
    print("=" * 60)

    if dry_run:
        print("\n[DRY-RUN] Each round:")
        print("  1. circuit_breaker.py  — check if loop should continue")
        print("  2. observe.py          — generate state report")
        print("  3. prompt.py           — assemble AI task")
        print("  4. [AI AGENT]          — execute changes")
        print("  5. guardrail.py        — validate changes")
        print("  6. [COLLECTORS]        — gather signals")
        print("  7. [JUDGES]            — evaluate signals")
        print("  8. PASS → merge | FAIL → rollback")
        print("  9. history update → next round")
        return

    round_num = 0
    for round_num in range(1, max_rounds + 1):
        elapsed_min = (time.time() - start_time) / 60

        print(f"\n{'━' * 60}")
        print(f"  Round {round_num}/{max_rounds}  |  {elapsed_min:.0f}m elapsed")
        print(f"{'━' * 60}")

        # --- Time check ---
        if elapsed_min >= max_duration_min:
            print(f"  Time limit reached ({max_duration_min}m). Stopping.")
            break

        # --- Step 1: Circuit breaker ---
        print("\n  [1] Circuit breaker...")
        cb_result = py_run("circuit_breaker.py", signals_dir, config_path)

        if cb_result.returncode == 2:
            print("  HALT — Stopping loop.")
            break
        elif cb_result.returncode == 1:
            print("  PAUSE — Human review needed.")
            print("  Waiting for human to approve: touch .signals/human_approved")

            approved_marker = os.path.join(signals_dir, "human_approved")
            while not os.path.exists(approved_marker):
                time.sleep(10)
            os.remove(approved_marker)
            print("  Human approved. Continuing.")

        # --- Step 2: Observe ---
        print("\n  [2] Observing current state...")
        py_run("observe.py", signals_dir)

        # --- Step 3: Generate prompt ---
        print("\n  [3] Generating AI task prompt...")
        py_run("prompt.py", signals_dir, config_path)

        prompt_path = os.path.join(signals_dir, "prompt.md")

        # --- Step 4: AI execution ---
        print("\n  [4] AI agent executing...")

        # 创建特性分支
        branch = f"evolve/round-{round_num}"
        git("checkout", base_branch)
        git("checkout", "-b", branch)

        # === AI AGENT — Claude Code CLI 直接调用 ===
        # -p          非交互模式，执行完自动退出
        # --allowedTools  只授权需要的工具，不用 --dangerously-skip-permissions
        # --max-turns 每轮最多 10 次 tool call，防止无限循环
        print(f"  Invoking claude CLI with prompt: {prompt_path}")
        round_start = time.time()

        if not os.path.exists(prompt_path):
            print(f"  prompt.py produced no output. Skipping round.")
            git("checkout", base_branch)
            git("branch", "-D", branch)
            continue

        prompt_content = Path(prompt_path).read_text(encoding="utf-8")
        # 捕获 AI 输出用于失败后诊断（self-heal 上下文传递）
        agent_log_path = os.path.join(signals_dir, "agent_output.log")
        with open(agent_log_path, "w", encoding="utf-8") as agent_log:
            claude_result = subprocess.run(
                [
                    "claude",
                    "-p", prompt_content,
                    "--allowedTools", "Bash,Read,Edit,Write",
                    "--max-turns", "10",
                ],
                stdout=agent_log,
                stderr=subprocess.STDOUT,
                timeout=1800,   # 30 分钟超时
            )

        if claude_result.returncode != 0:
            print(f"  claude CLI exited with code {claude_result.returncode}. Treating as FAIL.")
            # 读取 AI 留下的 self-heal-log（如果有），保存到 signals_dir
            _capture_self_heal_context(branch, signals_dir)
            git("checkout", base_branch)
            git("branch", "-D", branch)
            continue

        # --- Step 5: Guardrail ---
        print("\n  [5] Running guardrail checks...")
        gr_result = py_run("guardrail.py", config_path, "--base-ref", base_branch)

        if gr_result.returncode != 0:
            print("  BLOCKED by guardrail. Discarding changes.")
            _capture_self_heal_context(branch, signals_dir)
            git("checkout", base_branch)
            git("branch", "-D", branch)
            continue

        # --- Step 6 & 7: Collect + Judge (via orchestrator) ---
        print("\n  [6-7] Running signal collectors and judges...")
        all_pass = True

        for sig_cfg in signals:
            name = sig_cfg["name"]
            judge_path = str(SCRIPT_DIR / sig_cfg["judge"])
            collector_path = str(SCRIPT_DIR / sig_cfg["collector"])
            sig_config_path = str(SCRIPT_DIR / sig_cfg["config"])
            baseline_path = sig_cfg["baseline"]
            results_dir = sig_cfg["results_dir"]

            round_results = os.path.join(results_dir, f"round_{round_num}")
            os.makedirs(round_results, exist_ok=True)

            # Collect
            print(f"    [{name}] Collecting...")
            try:
                subprocess.run(
                    ["bash", collector_path, sig_config_path, round_results],
                    check=True, timeout=300,
                )
            except Exception as e:
                print(f"    [{name}] Collector failed: {e}")
                all_pass = False
                break

            # Judge
            print(f"    [{name}] Judging...")
            verdict_path = os.path.join(round_results, "verdict.json")

            mode = sig_cfg.get("mode", "median")
            if mode == "single":
                result_file = os.path.join(round_results, "result_1.json")
                judge_r = subprocess.run([
                    sys.executable, judge_path,
                    sig_config_path, baseline_path, result_file, verdict_path,
                ])
            else:
                judge_r = subprocess.run([
                    sys.executable, judge_path,
                    sig_config_path, baseline_path, round_results, verdict_path,
                ])

            if judge_r.returncode != 0:
                all_pass = False
                if merge_strategy == "all":
                    print(f"    [{name}] FAIL — skipping remaining signals")
                    break

            if os.path.exists(verdict_path):
                with open(verdict_path, encoding="utf-8") as f:
                    v = json.load(f)
                print(f"    [{name}] → {v.get('verdict', '?')}: {v.get('summary', '')}")

        round_duration = int(time.time() - round_start)

        # --- Step 8: Merge or rollback ---
        # 取分支上所有 commit 的摘要（用于 squash commit message）
        branch_log, _ = git("log", f"{base_branch}..{branch}", "--pretty=format:%s")
        description = branch_log.split("\n")[0] if branch_log else f"round {round_num}"

        if all_pass:
            print(f"\n  ALL PASS → Squash merging to {base_branch}")
            git("checkout", base_branch)
            _, squash_rc = git("merge", "--squash", branch)
            if squash_rc != 0:
                print(f"  Squash merge failed. Cleaning up.")
                _capture_self_heal_context(branch, signals_dir)
                git("reset", "--hard", "HEAD")
                git("branch", "-D", branch)
                all_pass = False
            else:
                _, commit_rc = git("commit", "-m", f"evolve: round {round_num} — {description}")
                if commit_rc != 0:
                    print(f"  Commit failed. Cleaning up.")
                    _capture_self_heal_context(branch, signals_dir)
                    git("reset", "--hard", "HEAD")
                    all_pass = False
                git("branch", "-D", branch)
        else:
            print(f"\n  FAIL → Discarding {branch}")
            _capture_self_heal_context(branch, signals_dir)
            git("checkout", base_branch)
            git("branch", "-D", branch)

        # 获取合并后的 commit SHA（用于 trajectory 归因）
        merged_sha = ""
        if all_pass:
            merged_sha, _ = git("rev-parse", "HEAD")

        # 读取 prompt 元数据（用于 AI 配置归因）
        prompt_meta = {}
        prompt_meta_path = os.path.join(signals_dir, "prompt_meta.json")
        if os.path.exists(prompt_meta_path):
            with open(prompt_meta_path, encoding="utf-8") as f:
                prompt_meta = json.load(f)

        # --- Step 9: Update history ---
        # (History is updated by individual judges via history.py,
        #  or by the orchestrator. For standalone driver, update trajectory.)
        traj_path = os.path.join(signals_dir, "trajectory.jsonl")
        os.makedirs(signals_dir, exist_ok=True)
        entry = {
            "round": round_num,
            "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "description": description or f"round {round_num}",
            "overall": "PASS" if all_pass else "FAIL",
            "commit_sha": merged_sha,
            "template_hash": prompt_meta.get("template_hash", ""),
            "prompt_hash": prompt_meta.get("prompt_hash", ""),
            "strategy_level": prompt_meta.get("strategy_level", 0),
            "duration_sec": round_duration,
        }
        with open(traj_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")

        # 每轮结束刷新仪表盘
        dashboard_script = SCRIPT_DIR / "dashboard.py"
        if dashboard_script.exists():
            subprocess.run(
                [sys.executable, str(dashboard_script), signals_dir],
                capture_output=True,
            )

    # --- Final report ---
    total_min = (time.time() - start_time) / 60

    # 读取完整 trajectory 生成验收报告
    all_trajectory = []
    traj_path = os.path.join(signals_dir, "trajectory.jsonl")
    if os.path.exists(traj_path):
        with open(traj_path, encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    all_trajectory.append(json.loads(line))

    report_path = generate_report(signals_dir, goal, all_trajectory, start_time, round_num)

    print(f"\n{'=' * 60}")
    print(f"  Evolution Loop Complete")
    print(f"  Duration: {total_min:.0f}m")
    print(f"  Report: {report_path}")
    print(f"{'=' * 60}")

    # 如果有阻断，打印诊断摘要
    diag_path = os.path.join(signals_dir, "blocker-diagnosis.md")
    if os.path.exists(diag_path):
        print(f"\n  ⚠ Blockers detected — see {diag_path}")
        with open(diag_path, encoding="utf-8") as f:
            for line in f.readlines()[:10]:
                print(f"    {line.rstrip()}")


if __name__ == "__main__":
    main()
